# permissions for end users to edit gbase8sclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit-role
rules:
- apiGroups:
  - gbase8s.gbase.cn
  resources:
  - gbase8sclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gbase8s.gbase.cn
  resources:
  - gbase8sclusters/status
  verbs:
  - get
  - patch
  - update

- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - jobs
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch

- apiGroups:
  - ""
  resources:
  - pods/status
  - pods/exec
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
