apiVersion: v1
kind: Service
metadata:
  name: cm-service
spec:
  type: NodePort
  ports:
    - name: redirect
      port: 10000
      targetPort: 10000
      nodePort: 31110
    - name: proxy
      port: 10001
      targetPort: 10001
      nodePort: 31111
  selector:
    cm: cm-gbase8s-cluster1