apiVersion: v1
kind: Service
metadata:
  name: gbase8s0
spec:
  type: NodePort
  ports:
    - name: python
      port: 8000
      targetPort: 8000
      nodePort: 31110
  selector:
    statefulset.kubernetes.io/pod-name: gc-gbase8s-cluster1-0

---
apiVersion: v1
kind: Service
metadata:
  name: gbase8s1
spec:
  type: NodePort
  ports:
    - name: python
      port: 8000
      targetPort: 8000
      nodePort: 31111
  selector:
    statefulset.kubernetes.io/pod-name: gc-gbase8s-cluster1-1

---
apiVersion: v1
kind: Service
metadata:
  name: gbase8s2
spec:
  type: NodePort
  ports:
    - name: python
      port: 8000
      targetPort: 8000
      nodePort: 31112
  selector:
    statefulset.kubernetes.io/pod-name: gc-gbase8s-cluster1-2