apiVersion: gbase8s.gbase.cn/v1
kind: Gbase8sCluster
metadata:
  name: gbase8s-cluster1
spec:
  # Add fields here
  # foo: bar
  #namespace: default
  gbase8s:
    replicas: 3
    image: gbase8s:8.8
    failover:
      detectingCount: 5
      detectingInterval: 2
      timeout: 5
    secretName: gbase8s-secret
    configMap:
      name: gbase8s-conf
      onconfigKey: onconfig.ol_gbasedbt_1
      allowedKey: allowed.surrogates
    nodes:
      - name: node1
        storage:
          path: /local/storage1
          size: 2Gi
          volumeMode: Filesystem
        log:
          path: /local/log1
          size: 2Gi
          volumeMode: Filesystem
      - name: master
        storage:
          path: /local/storage2
          size: 2Gi
          volumeMode: Filesystem
        log:
          path: /local/log2
          size: 2Gi
          volumeMode: Filesystem
      - name: master
        storage:
          path: /local/storage3
          size: 2Gi
          volumeMode: Filesystem
        log:
          path: /local/log3
          size: 2Gi
          volumeMode: Filesystem
  connectManager:
    replicas: 1
    image: cm:8.8
    secretName: gbase8s-secret
    redirectGroupName: cmredirect
    proxyGroupName: cmproxy
    configMap:
      name: gbase8s-conf
      configKey: cfg.cm
    nodes:
      - name: master
        log:
          path: /local/cmlog1
          size: 2Gi
          volumeMode: Filesystem
      - name: master
        log:
          path: /local/cmlog2
          size: 2Gi
          volumeMode: Filesystem
      - name: master
        log:
          path: /local/cmlog3
          size: 2Gi
          volumeMode: Filesystem