apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gbase8s-cluster.secret" . }}
type: Opaque
data:
  # 需要base64转码
  cm-password: {{ .Values.cmPassword | default "gbasedbt123" | b64enc }}
  gbase8s-password: {{ .Values.gbase8sPassword | default "gbaesdbt123" | b64enc }}